name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch name if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Change this to the directory where your HTML files are located
          cname: your-custom-domain.com  # If you have a custom domain, specify it here
